name: master_push
on:
  push:
    branches:
      - 'master'
jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: cleanup
        run: rm -rf .git .github
      - name: copy file via ssh password
        uses: up9cloud/action-rsync@master
        env:
          HOST: ${{ secrets.scphost }}
          USER: ${{ secrets.scpuser }}
          KEY: ${{ secrets.scpkey }}
          TARGET: /home/web/www.coldclimate.co.uk/
          SOURCE: .
